# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ruby on Rails and other forms of transportation
tagline:          Thoughts on programming
description:   'Rails and other interests blog'
#url:                 http://kenmcfadden.com
baseurl:             /
# enable pagination and set items per page..
paginate:            5

# About/contact
author:
  name:              ken mcfadden
  url:
  email:             kendmcfadden@gmail.com

# Custom vars
version:             1.0.0
