# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true      took out 1/7/17 build error via github

# Setup
title:         ken mcfadden / {"Dad":"1", "Learner":"2", "Developer-Coder":"3"}
tagline:       Notes on code
description:  'Rails and iSeries/midrange notes.'
#url:                 http://kenmcfadden.com
baseurl:             /
# enable pagination and set items per page..
paginate:            5

# About/contact
author:
  name:              ken mcfadden
  url:
  email:             kendmcfadden@gmail.com

# Custom vars
version:             1.0.0

kramdown:
  input: GFM
